services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
